---
- hosts: "{{ host }}"
  become: yes
  tasks:
    - name: Download Zabbix repository package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-agent2-6.4.3-release1.el7.x86_64.rpm"
        dest: /tmp/zabbix-agent2-6.4.3-release1.el7.x86_64.rpm

    - name: Install Zabbix Agent
      yum:
        name: /tmp/zabbix-agent2-6.4.3-release1.el7.x86_64.rpm
        state: present

    - name: Restart Zabbix Agent 2
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes
