---
- name: Download Zabbix repository package
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
    dest: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb

- name: Install Zabbix repository package
  apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb

- name: Install Zabbix Agent 2 and plugins
  apt:
    pkg:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    update_cache: yes

- name: Restart Zabbix Agent 2
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
